Make storageClassName configurable
solarwinds/swi-k8s-opentelemetry-collector pull request #833
Opened 2024-12-10 13:26 UTC by etichy

2024-12-10 15:36 UTC, pstranak-sw requested changes

2024-12-10 15:36 UTC, pstranak-sw commented on deploy/helm/values.schema.json
> +        },
We add `k8s` prefix to definitions, that are defined by Kubernetes. Also, the definition itself seems wrong. The `storageClassName` is an optional string, not an objet.
```suggestion
        "k8sStorageClassName": {
            "description": "The name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class",
            "type": [
                "string",
                "null"
            ]
        },
```

2024-12-10 15:36 UTC, pstranak-sw commented on deploy/helm/values.schema.json
> +                    "$ref": "#/definitions/storageClassName"
related to the other comment:
```suggestion
                    "$ref": "#/definitions/k8sStorageClassName"
```

2024-12-10 15:36 UTC, pstranak-sw commented on deploy/helm/values.schema.json
Also add the default (undefined) value to the `values.yaml`. Not strictly necessary, but we add all default values there.
```diff
diff --git a/deploy/helm/values.yaml b/deploy/helm/values.yaml
index ef0b673..421ff19 100644
--- a/deploy/helm/values.yaml
+++ b/deploy/helm/values.yaml
@@ -690,6 +690,7 @@ swoagent:
       cpu: 100m
   nodeSelector: {}
   affinity: {}
+  storageClassName:
 
 aws_fargate:
   # Enable support for AWS EKS Fargate environment
```

2024-12-12 07:55 UTC, etichy commented on deploy/helm/values.schema.json
done, thanks 👍

2024-12-12 09:08 UTC, pstranak-sw approved these changes

2024-12-13 09:02 UTC, merged